import type { ImageSourcePropType } from 'react-native';
import type { AvatarConfig } from '../../types';

/**
 * Avatar render packs. The full 6 skin tones x 3 hair looks (Long / Bob /
 * Blonde) matrix is pre-rendered with Higgsfield as 8-view turnarounds and
 * sliced into transparent frames, so every studio choice maps to a real,
 * distinct pack. packFor is an exact lookup, no approximation.
 *
 * GENERATED by design tooling (scratchpad/build_packs.js). Do not hand-edit
 * the require table; regenerate when packs change.
 */
export interface AvatarPack {
  /** Ordered clockwise, frame 0 = facing the camera. */
  frames: ImageSourcePropType[];
  /** Source aspect ratio, width / height. */
  aspect: number;
}

export const HAIR_LOOK_COUNT = 3;
export const SKIN_TONE_COUNT = 6;

/** PACKS[skinTone][hairLook] */
export const PACKS: AvatarPack[][] = [
  [
    { aspect: 0.4304, frames: [
      require('../../../assets/avatar/packs/s0_long/f0.png'),
      require('../../../assets/avatar/packs/s0_long/f1.png'),
      require('../../../assets/avatar/packs/s0_long/f2.png'),
      require('../../../assets/avatar/packs/s0_long/f3.png'),
      require('../../../assets/avatar/packs/s0_long/f4.png'),
      require('../../../assets/avatar/packs/s0_long/f5.png'),
      require('../../../assets/avatar/packs/s0_long/f6.png'),
      require('../../../assets/avatar/packs/s0_long/f7.png'),
    ] },
    { aspect: 0.4364, frames: [
      require('../../../assets/avatar/packs/s0_bob/f0.png'),
      require('../../../assets/avatar/packs/s0_bob/f1.png'),
      require('../../../assets/avatar/packs/s0_bob/f2.png'),
      require('../../../assets/avatar/packs/s0_bob/f3.png'),
      require('../../../assets/avatar/packs/s0_bob/f4.png'),
      require('../../../assets/avatar/packs/s0_bob/f5.png'),
      require('../../../assets/avatar/packs/s0_bob/f6.png'),
      require('../../../assets/avatar/packs/s0_bob/f7.png'),
    ] },
    { aspect: 0.3942, frames: [
      require('../../../assets/avatar/packs/s0_blonde/f0.png'),
      require('../../../assets/avatar/packs/s0_blonde/f1.png'),
      require('../../../assets/avatar/packs/s0_blonde/f2.png'),
      require('../../../assets/avatar/packs/s0_blonde/f3.png'),
      require('../../../assets/avatar/packs/s0_blonde/f4.png'),
      require('../../../assets/avatar/packs/s0_blonde/f5.png'),
      require('../../../assets/avatar/packs/s0_blonde/f6.png'),
      require('../../../assets/avatar/packs/s0_blonde/f7.png'),
    ] },
  ],
  [
    { aspect: 0.3461, frames: [
      require('../../../assets/avatar/packs/s1_long/f0.png'),
      require('../../../assets/avatar/packs/s1_long/f1.png'),
      require('../../../assets/avatar/packs/s1_long/f2.png'),
      require('../../../assets/avatar/packs/s1_long/f3.png'),
      require('../../../assets/avatar/packs/s1_long/f4.png'),
      require('../../../assets/avatar/packs/s1_long/f5.png'),
      require('../../../assets/avatar/packs/s1_long/f6.png'),
      require('../../../assets/avatar/packs/s1_long/f7.png'),
    ] },
    { aspect: 0.3437, frames: [
      require('../../../assets/avatar/packs/s1_bob/f0.png'),
      require('../../../assets/avatar/packs/s1_bob/f1.png'),
      require('../../../assets/avatar/packs/s1_bob/f2.png'),
      require('../../../assets/avatar/packs/s1_bob/f3.png'),
      require('../../../assets/avatar/packs/s1_bob/f4.png'),
      require('../../../assets/avatar/packs/s1_bob/f5.png'),
      require('../../../assets/avatar/packs/s1_bob/f6.png'),
      require('../../../assets/avatar/packs/s1_bob/f7.png'),
    ] },
    { aspect: 0.4339, frames: [
      require('../../../assets/avatar/packs/s1_blonde/f0.png'),
      require('../../../assets/avatar/packs/s1_blonde/f1.png'),
      require('../../../assets/avatar/packs/s1_blonde/f2.png'),
      require('../../../assets/avatar/packs/s1_blonde/f3.png'),
      require('../../../assets/avatar/packs/s1_blonde/f4.png'),
      require('../../../assets/avatar/packs/s1_blonde/f5.png'),
      require('../../../assets/avatar/packs/s1_blonde/f6.png'),
      require('../../../assets/avatar/packs/s1_blonde/f7.png'),
    ] },
  ],
  [
    { aspect: 0.4269, frames: [
      require('../../../assets/avatar/packs/s2_long/f0.png'),
      require('../../../assets/avatar/packs/s2_long/f1.png'),
      require('../../../assets/avatar/packs/s2_long/f2.png'),
      require('../../../assets/avatar/packs/s2_long/f3.png'),
      require('../../../assets/avatar/packs/s2_long/f4.png'),
      require('../../../assets/avatar/packs/s2_long/f5.png'),
      require('../../../assets/avatar/packs/s2_long/f6.png'),
      require('../../../assets/avatar/packs/s2_long/f7.png'),
    ] },
    { aspect: 0.358, frames: [
      require('../../../assets/avatar/packs/s2_bob/f0.png'),
      require('../../../assets/avatar/packs/s2_bob/f1.png'),
      require('../../../assets/avatar/packs/s2_bob/f2.png'),
      require('../../../assets/avatar/packs/s2_bob/f3.png'),
      require('../../../assets/avatar/packs/s2_bob/f4.png'),
      require('../../../assets/avatar/packs/s2_bob/f5.png'),
      require('../../../assets/avatar/packs/s2_bob/f6.png'),
      require('../../../assets/avatar/packs/s2_bob/f7.png'),
    ] },
    { aspect: 0.384, frames: [
      require('../../../assets/avatar/packs/s2_blonde/f0.png'),
      require('../../../assets/avatar/packs/s2_blonde/f1.png'),
      require('../../../assets/avatar/packs/s2_blonde/f2.png'),
      require('../../../assets/avatar/packs/s2_blonde/f3.png'),
      require('../../../assets/avatar/packs/s2_blonde/f4.png'),
      require('../../../assets/avatar/packs/s2_blonde/f5.png'),
      require('../../../assets/avatar/packs/s2_blonde/f6.png'),
      require('../../../assets/avatar/packs/s2_blonde/f7.png'),
    ] },
  ],
  [
    { aspect: 0.4296, frames: [
      require('../../../assets/avatar/packs/s3_long/f0.png'),
      require('../../../assets/avatar/packs/s3_long/f1.png'),
      require('../../../assets/avatar/packs/s3_long/f2.png'),
      require('../../../assets/avatar/packs/s3_long/f3.png'),
      require('../../../assets/avatar/packs/s3_long/f4.png'),
      require('../../../assets/avatar/packs/s3_long/f5.png'),
      require('../../../assets/avatar/packs/s3_long/f6.png'),
      require('../../../assets/avatar/packs/s3_long/f7.png'),
    ] },
    { aspect: 0.387, frames: [
      require('../../../assets/avatar/packs/s3_bob/f0.png'),
      require('../../../assets/avatar/packs/s3_bob/f1.png'),
      require('../../../assets/avatar/packs/s3_bob/f2.png'),
      require('../../../assets/avatar/packs/s3_bob/f3.png'),
      require('../../../assets/avatar/packs/s3_bob/f4.png'),
      require('../../../assets/avatar/packs/s3_bob/f5.png'),
      require('../../../assets/avatar/packs/s3_bob/f6.png'),
      require('../../../assets/avatar/packs/s3_bob/f7.png'),
    ] },
    { aspect: 0.4337, frames: [
      require('../../../assets/avatar/packs/s3_blonde/f0.png'),
      require('../../../assets/avatar/packs/s3_blonde/f1.png'),
      require('../../../assets/avatar/packs/s3_blonde/f2.png'),
      require('../../../assets/avatar/packs/s3_blonde/f3.png'),
      require('../../../assets/avatar/packs/s3_blonde/f4.png'),
      require('../../../assets/avatar/packs/s3_blonde/f5.png'),
      require('../../../assets/avatar/packs/s3_blonde/f6.png'),
      require('../../../assets/avatar/packs/s3_blonde/f7.png'),
    ] },
  ],
  [
    { aspect: 0.4521, frames: [
      require('../../../assets/avatar/packs/s4_long/f0.png'),
      require('../../../assets/avatar/packs/s4_long/f1.png'),
      require('../../../assets/avatar/packs/s4_long/f2.png'),
      require('../../../assets/avatar/packs/s4_long/f3.png'),
      require('../../../assets/avatar/packs/s4_long/f4.png'),
      require('../../../assets/avatar/packs/s4_long/f5.png'),
      require('../../../assets/avatar/packs/s4_long/f6.png'),
      require('../../../assets/avatar/packs/s4_long/f7.png'),
    ] },
    { aspect: 0.4087, frames: [
      require('../../../assets/avatar/packs/s4_bob/f0.png'),
      require('../../../assets/avatar/packs/s4_bob/f1.png'),
      require('../../../assets/avatar/packs/s4_bob/f2.png'),
      require('../../../assets/avatar/packs/s4_bob/f3.png'),
      require('../../../assets/avatar/packs/s4_bob/f4.png'),
      require('../../../assets/avatar/packs/s4_bob/f5.png'),
      require('../../../assets/avatar/packs/s4_bob/f6.png'),
      require('../../../assets/avatar/packs/s4_bob/f7.png'),
    ] },
    { aspect: 0.4146, frames: [
      require('../../../assets/avatar/packs/s4_blonde/f0.png'),
      require('../../../assets/avatar/packs/s4_blonde/f1.png'),
      require('../../../assets/avatar/packs/s4_blonde/f2.png'),
      require('../../../assets/avatar/packs/s4_blonde/f3.png'),
      require('../../../assets/avatar/packs/s4_blonde/f4.png'),
      require('../../../assets/avatar/packs/s4_blonde/f5.png'),
      require('../../../assets/avatar/packs/s4_blonde/f6.png'),
      require('../../../assets/avatar/packs/s4_blonde/f7.png'),
    ] },
  ],
  [
    { aspect: 0.4566, frames: [
      require('../../../assets/avatar/packs/s5_long/f0.png'),
      require('../../../assets/avatar/packs/s5_long/f1.png'),
      require('../../../assets/avatar/packs/s5_long/f2.png'),
      require('../../../assets/avatar/packs/s5_long/f3.png'),
      require('../../../assets/avatar/packs/s5_long/f4.png'),
      require('../../../assets/avatar/packs/s5_long/f5.png'),
      require('../../../assets/avatar/packs/s5_long/f6.png'),
      require('../../../assets/avatar/packs/s5_long/f7.png'),
    ] },
    { aspect: 0.3491, frames: [
      require('../../../assets/avatar/packs/s5_bob/f0.png'),
      require('../../../assets/avatar/packs/s5_bob/f1.png'),
      require('../../../assets/avatar/packs/s5_bob/f2.png'),
      require('../../../assets/avatar/packs/s5_bob/f3.png'),
      require('../../../assets/avatar/packs/s5_bob/f4.png'),
      require('../../../assets/avatar/packs/s5_bob/f5.png'),
      require('../../../assets/avatar/packs/s5_bob/f6.png'),
      require('../../../assets/avatar/packs/s5_bob/f7.png'),
    ] },
    { aspect: 0.4156, frames: [
      require('../../../assets/avatar/packs/s5_blonde/f0.png'),
      require('../../../assets/avatar/packs/s5_blonde/f1.png'),
      require('../../../assets/avatar/packs/s5_blonde/f2.png'),
      require('../../../assets/avatar/packs/s5_blonde/f3.png'),
      require('../../../assets/avatar/packs/s5_blonde/f4.png'),
      require('../../../assets/avatar/packs/s5_blonde/f5.png'),
      require('../../../assets/avatar/packs/s5_blonde/f6.png'),
      require('../../../assets/avatar/packs/s5_blonde/f7.png'),
    ] },
  ],
];

const clamp = (v: number, hi: number) => (v < 0 ? 0 : v > hi ? hi : v | 0);

export function packFor(avatar?: AvatarConfig | null): AvatarPack {
  const sk = clamp(avatar?.skinTone ?? 0, 5);
  const look = clamp(avatar?.hairLook ?? 0, 2);
  return PACKS[sk][look];
}

export function frontFor(skinTone: number, hairLook: number): ImageSourcePropType {
  return PACKS[clamp(skinTone, 5)][clamp(hairLook, 2)].frames[0];
}

export const DEFAULT_PACK: AvatarPack = PACKS[0][0];
